In [ ]:
import sqlite3
from pathlib import Path
import numpy as np
import pandas as pd

In [3]:
db_path = Path("../../data/database.sqlite")

conn = sqlite3.connect(db_path.as_posix())

df = pd.read_sql_query("SELECT * FROM Match_Aggregated", conn)

conn.close()

# Extract Player Stats

In [78]:
player_stats_cols = [
    "preferred_foot",
    "attacking_work_rate",
    "defensive_work_rate",
    "crossing",
    "finishing",
    "heading_accuracy",
    "short_passing",
    "volleys",
    "dribbling",
    "curve",
    "free_kick_accuracy",
    "long_passing",
    "ball_control",
    "acceleration",
    "sprint_speed",
    "agility",
    "reactions",
    "balance",
    "shot_power",
    "jumping",
    "stamina",
    "strength",
    "long_shots",
    "aggression",
    "interceptions",
    "positioning",
    "vision",
    "penalties",
    "marking",
    "standing_tackle",
    "sliding_tackle",
]

In [77]:
pd.set_option("display.max_columns", None)
df[player_stats_cols].describe()

,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,height,weight
count,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000
mean,0.261685,1.209822,1.109396,61.353916,53.155545,64.054269,68.906245,53.173838,64.241178,57.609096,53.665077,62.781607,69.510999,70.357781,70.971574,67.925269,69.898811,67.724652,66.708038,68.853665,72.348914,70.401201,58.053462,67.212645,59.974070,61.090967,63.474810,59.250866,54.608429,58.609552,55.907202,181.465509,168.112951
std,0.439552,0.526241,0.521087,13.980780,18.115181,12.083587,9.275423,17.163142,13.894278,15.902317,16.438778,11.465399,9.516477,11.169773,10.571189,11.649277,8.315567,11.597050,12.933071,10.637541,9.639156,10.822324,16.529316,13.290894,17.833215,16.290478,12.904476,14.244328,20.733784,20.111370,20.618971,6.157523,14.347130
min,0.000000,0.000000,0.000000,9.000000,7.000000,7.000000,15.000000,4.000000,8.000000,7.000000,6.000000,13.000000,15.000000,21.000000,20.000000,19.000000,27.000000,25.000000,7.000000,20.000000,21.000000,20.000000,6.000000,11.000000,10.000000,8.000000,11.000000,8.000000,7.000000,8.000000,4.000000,157.480000,117.000000
25%,0.000000,1.000000,1.000000,53.000000,39.000000,56.000000,63.000000,40.000000,57.000000,46.000000,41.000000,56.000000,64.000000,65.000000,66.000000,61.000000,65.000000,61.000000,60.000000,63.000000,67.000000,64.000000,48.000000,60.000000,48.000000,52.000000,56.000000,50.000000,35.000000,41.000000,37.000000,177.800000,159.000000
50%,0.000000,1.000000,1.000000,64.000000,55.000000,65.000000,69.000000,55.000000,67.000000,59.000000,54.000000,64.000000,70.000000,71.000000,72.000000,69.000000,70.000000,69.000000,69.000000,70.000000,73.000000,72.000000,61.000000,70.000000,65.000000,65.000000,65.000000,60.000000,62.000000,66.000000,63.000000,182.880000,168.000000
75%,1.000000,2.000000,1.000000,72.000000,68.000000,73.000000,75.000000,67.000000,74.000000,70.000000,67.000000,71.000000,76.000000,78.000000,78.000000,76.000000,76.000000,75.000000,76.000000,76.000000,79.000000,78.000000,70.000000,77.000000,73.000000,73.000000,73.000000,70.000000,71.000000,75.000000,73.000000,185.420000,176.000000
max,1.000000,2.000000,2.000000,95.000000,97.000000,95.000000,97.000000,93.000000,97.000000,94.000000,96.000000,97.000000,97.000000,97.000000,97.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,96.000000,97.000000,96.000000,96.000000,97.000000,96.000000,93.000000,95.000000,95.000000,203.200000,225.000000

In [79]:
# Scale from 0 - 2 to -1 - 1
df[["attacking_work_rate", "defensive_work_rate"]] = (
    df[["attacking_work_rate", "defensive_work_rate"]] - 1
)

# Scale from 0 - 100 to -1 - 1
scale_cols = [
    "crossing",
    "finishing",
    "heading_accuracy",
    "short_passing",
    "volleys",
    "dribbling",
    "curve",
    "free_kick_accuracy",
    "long_passing",
    "ball_control",
    "acceleration",
    "sprint_speed",
    "agility",
    "reactions",
    "balance",
    "shot_power",
    "jumping",
    "stamina",
    "strength",
    "long_shots",
    "aggression",
    "interceptions",
    "positioning",
    "vision",
    "penalties",
    "marking",
    "standing_tackle",
    "sliding_tackle",
]
df[scale_cols] = (df[scale_cols] / 50) - 1

df_player = df[player_stats_cols]

In [80]:
df_player.describe()

,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle
count,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.00000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000,427220.000000
mean,0.261685,0.209822,0.109396,0.227078,0.063111,0.281085,0.378125,0.063477,0.284824,0.152182,0.073302,0.255632,0.39022,0.407156,0.419431,0.358505,0.397976,0.354493,0.334161,0.377073,0.446978,0.408024,0.161069,0.344253,0.199481,0.221819,0.269496,0.185017,0.092169,0.172191,0.118144
std,0.439552,0.526241,0.521087,0.279616,0.362304,0.241672,0.185508,0.343263,0.277886,0.318046,0.328776,0.229308,0.19033,0.223395,0.211424,0.232986,0.166311,0.231941,0.258661,0.212751,0.192783,0.216446,0.330586,0.265818,0.356664,0.325810,0.258090,0.284887,0.414676,0.402227,0.412379
min,0.000000,-1.000000,-1.000000,-0.820000,-0.860000,-0.860000,-0.700000,-0.920000,-0.840000,-0.860000,-0.880000,-0.740000,-0.70000,-0.580000,-0.600000,-0.620000,-0.460000,-0.500000,-0.860000,-0.600000,-0.580000,-0.600000,-0.880000,-0.780000,-0.800000,-0.840000,-0.780000,-0.840000,-0.860000,-0.840000,-0.920000
25%,0.000000,0.000000,0.000000,0.060000,-0.220000,0.120000,0.260000,-0.200000,0.140000,-0.080000,-0.180000,0.120000,0.28000,0.300000,0.320000,0.220000,0.300000,0.220000,0.200000,0.260000,0.340000,0.280000,-0.040000,0.200000,-0.040000,0.040000,0.120000,0.000000,-0.300000,-0.180000,-0.260000
50%,0.000000,0.000000,0.000000,0.280000,0.100000,0.300000,0.380000,0.100000,0.340000,0.180000,0.080000,0.280000,0.40000,0.420000,0.440000,0.380000,0.400000,0.380000,0.380000,0.400000,0.460000,0.440000,0.220000,0.400000,0.300000,0.300000,0.300000,0.200000,0.240000,0.320000,0.260000
75%,1.000000,1.000000,0.000000,0.440000,0.360000,0.460000,0.500000,0.340000,0.480000,0.400000,0.340000,0.420000,0.52000,0.560000,0.560000,0.520000,0.520000,0.500000,0.520000,0.520000,0.580000,0.560000,0.400000,0.540000,0.460000,0.460000,0.460000,0.400000,0.420000,0.500000,0.460000
max,1.000000,1.000000,1.000000,0.900000,0.940000,0.900000,0.940000,0.860000,0.940000,0.880000,0.920000,0.940000,0.94000,0.940000,0.940000,0.920000,0.920000,0.920000,0.920000,0.920000,0.920000,0.920000,0.920000,0.940000,0.920000,0.920000,0.940000,0.920000,0.860000,0.900000,0.900000

# Extract Formation Stats

In [ ]:
formation_data = []
for (_, team_side), df_group in df.groupby(["match_api_id", "team_side"]):
    # Extract relevant Columns
    df_player = df_group[player_stats_cols]
    df_position = df_group[["player_x", "player_y"]]

    # Normalize Player Positions
    np_position = df_position.to_numpy()
    np_position_normalized = (np_position - np_position.min(axis=0)) / (
        np_position.max(axis=0) - np_position.min(axis=0)
    )

    for i in range(np_position.shape[0]):
        # Extract Player
        current_player = np_position_normalized[i]
        other_players = np.delete(np_position_normalized, i, axis=0)

        # Calculate Distance
        relative_vectors = other_players - current_player
        distances = np.linalg.norm(relative_vectors, ord=2, axis=1)

        # Calculate Angle
        angles_rad = np.arctan2(relative_vectors[:, 1], relative_vectors[:, 0])

        formation_data.append(np.hstack([current_player, distances, angles_rad]))

In [53]:
formation_cols = (
    ["x", "y"]
    + [f"distance_{i + 1}" for i in range(9)]
    + [f"angle_{i + 1}" for i in range(9)]
)
df_formation = pd.DataFrame(formation_data, columns=formation_cols)

In [54]:
df_formation.head()

,x,y,distance_1,distance_2,distance_3,distance_4,distance_5,distance_6,distance_7,distance_8,distance_9,angle_1,angle_2,angle_3,angle_4,angle_5,angle_6,angle_7,angle_8,angle_9
0,0.000000,0.000000,1.000000,0.878052,1.151751,0.661545,0.333333,0.571429,1.054093,1.201850,0.666667,0.000000,0.708626,0.519146,1.042722,0.000000,1.570796,1.249046,0.982794,0.000000
1,1.000000,0.000000,1.000000,0.661545,0.571429,0.878052,0.666667,1.151751,1.201850,1.054093,0.333333,3.141593,2.098871,1.570796,2.432966,3.141593,2.622447,2.158799,1.892547,3.141593
2,0.666667,0.571429,0.878052,0.661545,0.333333,0.333333,0.661545,0.666667,0.542941,0.428571,0.571429,-2.432966,-1.042722,0.000000,3.141593,-2.098871,3.141593,2.231839,1.570796,-1.570796
3,1.000000,0.571429,1.151751,0.571429,0.333333,0.666667,0.878052,1.000000,0.792539,0.542941,0.661545,-2.622447,-1.570796,3.141593,3.141593,-2.432966,3.141593,2.570255,2.231839,-2.098871
4,0.333333,0.571429,0.661545,0.878052,0.333333,0.666667,0.571429,0.333333,0.428571,0.542941,0.661545,-2.098871,-0.708626,0.000000,0.000000,-1.570796,3.141593,1.570796,0.909753,-1.042722

# Concat Dataframes

In [84]:
df_final = pd.concat([df_player, df_formation], axis=1)

In [87]:
df_final.head()

,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,x,y,distance_1,distance_2,distance_3,distance_4,distance_5,distance_6,distance_7,distance_8,distance_9,angle_1,angle_2,angle_3,angle_4,angle_5,angle_6,angle_7,angle_8,angle_9
0,0.0,0.0,0.0,0.36,0.28,0.22,0.50,0.400000,0.44,0.500000,0.36,0.42,0.46,0.46,0.36,0.520000,0.40,0.380000,0.44,0.40000,0.44,0.36,0.60,0.26,0.36,0.32,0.500000,0.36,-0.34,-0.06,-0.280000,0.000000,0.000000,1.000000,0.878052,1.151751,0.661545,0.333333,0.571429,1.054093,1.201850,0.666667,0.000000,0.708626,0.519146,1.042722,0.000000,1.570796,1.249046,0.982794,0.000000
1,1.0,0.0,1.0,0.48,-0.14,0.20,0.30,-0.600000,0.14,0.300000,-0.04,0.16,0.28,0.36,0.38,0.400000,0.38,0.400000,-0.10,0.40000,0.46,0.40,-0.14,0.38,0.36,0.26,0.460000,0.34,0.36,0.38,0.380000,1.000000,0.000000,1.000000,0.661545,0.571429,0.878052,0.666667,1.151751,1.201850,1.054093,0.333333,3.141593,2.098871,1.570796,2.432966,3.141593,2.622447,2.158799,1.892547,3.141593
2,0.0,0.0,0.0,0.32,0.18,-0.36,0.46,0.340000,0.28,0.400000,0.24,0.36,0.44,0.54,0.56,0.520000,0.52,0.380000,0.14,0.04000,0.58,0.28,0.40,0.28,0.40,0.50,0.500000,0.40,0.26,0.08,0.100000,0.666667,0.571429,0.878052,0.661545,0.333333,0.333333,0.661545,0.666667,0.542941,0.428571,0.571429,-2.432966,-1.042722,0.000000,3.141593,-2.098871,3.141593,2.231839,1.570796,-1.570796
3,0.0,0.0,1.0,0.44,0.26,-0.24,0.26,-0.160000,0.38,-0.040000,0.06,0.30,0.40,0.58,0.56,0.280000,0.28,0.260000,0.28,0.46000,0.40,0.40,0.04,0.44,0.38,0.40,0.160000,0.22,0.38,0.44,0.400000,1.000000,0.571429,1.151751,0.571429,0.333333,0.666667,0.878052,1.000000,0.792539,0.542941,0.661545,-2.622447,-1.570796,3.141593,3.141593,-2.432966,3.141593,2.570255,2.231839,-2.098871
4,0.0,0.0,0.0,-0.54,-0.54,0.28,0.14,-0.519097,-0.46,-0.574571,-0.88,-0.06,0.16,0.08,0.24,0.023867,0.08,0.215362,-0.48,0.38738,0.32,0.38,-0.54,0.22,0.04,0.12,-0.008422,0.16,0.32,0.26,0.229861,0.333333,0.571429,0.661545,0.878052,0.333333,0.666667,0.571429,0.333333,0.428571,0.542941,0.661545,-2.098871,-0.708626,0.000000,0.000000,-1.570796,3.141593,1.570796,0.909753,-1.042722

In [88]:
conn = sqlite3.connect(db_path.as_posix())

df_final.to_sql(
    "Player_Formation_Preprocessed",
    conn,
    if_exists="replace",
    index=False,
)

conn.close()